file = open("test.txt")
print("file.read():\n",file.read())
file.close()
file = open("test.txt")
print("file.read(2):\n",file.read(2))
file.close()
file = open("test.txt")
print("file.readline():\n",file.readline())
file.close()
file = open("test.txt")
print("file.readline():\n",file.readline())
file.close()
